-- ============================================================
-- TRIPULSE — Carga masiva de la Biblioteca de Fuerza
-- 162 ejercicios · 18 grupos musculares
--
-- REQUISITO: ejecutar antes biblioteca-ejercicios-schema.sql
-- (crea la columna `ejecucion`).
--
-- IDEMPOTENTE: la clave logica es `nombre`. Reejecutar no duplica
-- (inserta solo lo que falta). Tampoco actualiza filas existentes:
-- si editas un texto aqui y quieres que baje a la BD, borra esa
-- fila primero o editala desde la app.
--
-- No crea indices ni altera el esquema.
-- url_video queda a NULL: se rellena desde la app (clave admin).
--
-- Campos:
--   descripcion → para que sirve en triatlon (se ve en la lista)
--   ejecucion   → tecnica paso a paso (se ve en el modal de detalle)
--
-- Fuentes: wiki Obsidian del usuario (B3-01 Fuerza General, B4-01
-- Fuerza por Disciplina, B5-01 Lesiones Carrera, B5-02 Lesiones
-- Ciclismo/Natacion, B6-08 Biomecanica Ciclismo). La tecnica de
-- sentadilla, peso muerto, RDL, hip thrust, dominadas, heel drop
-- de Alfredson, clamshell, step-down, bird-dog, dead bug, wall
-- slide y estiramiento de fascia es literal de esas notas. El
-- resto usa tecnica estandar de fuerza, complementada con material
-- publico de USA Triathlon, TrainingPeaks y StrengthLog.
-- ============================================================

insert into ejercicios_biblioteca (nombre, grupo_muscular, descripcion, ejecucion)
select v.nombre, v.grupo_muscular, v.descripcion, v.ejecucion
from (values

-- ---------- PECTORAL (7) ----------
('Press de banca con barra', 'Pectoral', 'Empuje horizontal: pectoral, deltoides anterior y triceps, los musculos de la fase de empuje de la brazada.', E'1) Tumbado, ojos bajo la barra, pies firmes en el suelo.\n2) Escapulas retraidas y deprimidas contra el banco durante toda la serie.\n3) Bajar la barra controlada hasta la linea del pecho, codos a unos 45 grados del torso.\n4) Empujar hasta extender codos sin bloquear con violencia.\n\nFuerza maxima: 3x3-6. Con hombro irritado, reducir el rango o pasar a mancuernas.'),
('Press de banca inclinado con mancuernas', 'Pectoral', 'Enfatiza el pectoral superior y el deltoides anterior con un recorrido mas libre que la barra.', E'1) Banco a 30-45 grados. Mancuernas a la altura del pecho.\n2) Palmas enfrentadas si el hombro esta irritado; pronadas si no.\n3) Empujar juntando ligeramente las mancuernas arriba, sin chocarlas.\n4) Bajar controlado hasta notar estiramiento sin forzar el hombro.'),
('Flexiones', 'Pectoral', 'Pectoral, hombro, triceps y core sin material. Suma estabilidad escapular y activacion del serrato, que se apaga con las horas en posicion aero.', E'1) Manos algo mas anchas que los hombros, cuerpo en linea recta de cabeza a talones.\n2) Bajar hasta que el pecho quede a un palmo del suelo, codos a 45 grados.\n3) Empujar sin dejar caer la cadera ni sacar el cuello.\n4) Arriba, empujar un poco mas para separar las escapulas: eso activa el serrato.\n\nSi la cadera se hunde, el core esta fallando: hacerlas con manos elevadas.'),
('Aperturas con mancuernas', 'Pectoral', 'Aislamiento del pectoral en aduccion horizontal.', E'1) Tumbado, mancuernas sobre el pecho, palmas enfrentadas.\n2) Abrir los brazos en arco con los codos ligeramente flexionados y FIJOS.\n3) Bajar solo hasta la altura del pecho, no mas: el rango extremo es donde se lesiona el hombro del nadador.\n4) Cerrar el arco con la misma trayectoria.'),
('Pullover con mancuerna', 'Pectoral', 'Trabaja pectoral y dorsal a la vez con el brazo sobre la cabeza, cerca del patron de entrada y agarre del crol.', E'1) Tumbado en banco, mancuerna sujeta con las dos manos sobre el pecho.\n2) Llevar la mancuerna por detras de la cabeza en arco, codos algo flexionados.\n3) Bajar solo hasta donde la movilidad de hombro permita sin arquear la lumbar.\n4) Volver contrayendo dorsal y pectoral.'),
('Fondos en paralelas', 'Pectoral', 'Empuje vertical: pectoral inferior y triceps. Exigente para el hombro.', E'1) Suspendido en paralelas, brazos extendidos, torso ligeramente inclinado adelante para cargar mas pectoral.\n2) Bajar controlado.\n3) NO bajar de 90 grados de codo: por debajo, la carga sobre la capsula anterior del hombro se dispara.\n4) Empujar hasta extension.\n\nSolo con buena movilidad de hombro y sin historial de dolor.'),
('Empuje isometrico en rack (iso-push)', 'Pectoral', 'Isometria de tipo overcoming: reclutamiento neural alto sin dano muscular, util cerca de competicion.', E'1) Barra apoyada en pines fijos a la altura del pecho, tumbado en banco.\n2) Empujar contra la barra al maximo durante 3-5 s. La barra no se mueve.\n3) Soltar la tension progresivamente, no de golpe.\n4) 4-5 repeticiones con 1-2 min entre ellas.\n\nAl no haber fase excentrica, casi no deja agujetas: por eso encaja en semanas de carga alta de resistencia.'),

-- ---------- ESPALDA ALTA Y ROMBOIDES (9) ----------
('Dominadas', 'Espalda alta y romboides', 'El ejercicio mas especifico para natacion: el patron es casi identico a la traccion del crol.', E'1) Agarre prono, anchura de hombros.\n2) Partir del descenso completo, con los brazos extendidos.\n3) Tirar hasta que la barbilla supere la barra.\n4) Bajar controlado hasta la extension completa otra vez.\n\nProgresion: principiante, jalon al pecho o banda de asistencia 3x10-12. Intermedio, peso corporal 4x5-8. Avanzado, con lastre 4x4-6 al 80% del peso corporal.'),
('Remo con mancuerna unilateral', 'Espalda alta y romboides', 'Dorsal en el patron de traccion unilateral del crol.', E'1) Rodilla y mano del mismo lado apoyadas en un banco, espalda plana y paralela al suelo.\n2) Mancuerna colgando con el brazo extendido.\n3) Tirar de la mancuerna HACIA LA CADERA, no hacia el hombro: esa trayectoria es la del crol.\n4) Bajar controlado sin girar el tronco.\n\n3x10-12 por lado.'),
('Remo con barra', 'Espalda alta y romboides', 'Dorsal, trapecio y erector con carga alta. Contrapesa la posicion aero y el dominio de cuadriceps del triatleta.', E'1) Bisagra de cadera hasta unos 45 grados de inclinacion, espalda neutra.\n2) Agarre prono algo mas ancho que los hombros.\n3) Tirar hacia el abdomen bajo, codos pegados al cuerpo.\n4) Bajar controlado sin redondear la espalda.\n\n3x6. Si el tronco se balancea para subir el peso, hay demasiada carga.'),
('Remo en polea baja sentado', 'Espalda alta y romboides', 'Traccion horizontal con tension constante y poca exigencia lumbar.', E'1) Sentado, rodillas algo flexionadas, espalda erguida.\n2) Tirar del agarre hacia el abdomen juntando las escapulas.\n3) Volver controlado dejando que las escapulas se separen, sin encorvarse.\n4) El tronco no se balancea: solo trabajan los brazos y la espalda.'),
('Remo invertido', 'Espalda alta y romboides', 'Traccion horizontal con peso corporal. Progresion hacia la dominada y muy escalable.', E'1) Barra a la altura de la cadera o anillas. Colgarse por debajo con el cuerpo en linea recta.\n2) Tirar del pecho hacia la barra, codos pegados.\n3) Bajar controlado manteniendo la linea del cuerpo.\n\nPara hacerlo mas facil, subir la barra o doblar las rodillas. Para hacerlo mas dificil, bajarla o elevar los pies.'),
('Remo horizontal con banda', 'Espalda alta y romboides', 'Equilibra el dominio de pectoral y dorsal frente a un manguito debil, que es el desequilibrio de fondo del hombro del nadador.', E'1) Banda anclada a la altura del pecho, un extremo en cada mano.\n2) Brazos extendidos, tirar hacia el abdomen juntando las escapulas.\n3) Volver controlado resistiendo la banda.\n\n3x15. Fase de rehabilitacion del hombro del nadador.'),
('Remo con banda para trapecios medios', 'Espalda alta y romboides', 'Previene la protraccion de hombros que alimenta la cervicalgia del ciclista en posicion de crono.', E'1) Banda anclada a la altura del pecho.\n2) Tirar con los codos pegados al cuerpo, cerrando las escapulas.\n3) Mantener 1 s la contraccion antes de volver.\n\n3x15.'),
('Band pull-apart', 'Espalda alta y romboides', 'Deltoides posterior y romboides con alto volumen y bajo riesgo. Ideal como calentamiento antes de nadar.', E'1) Banda sujeta con las dos manos, brazos extendidos al frente a la altura del pecho.\n2) Separar las manos abriendo el pecho hasta que la banda toque el esternon.\n3) Volver controlado, sin dejar que la banda tire de ti.\n\nBrazos rectos todo el rato. 2-3x15-20.'),
('Tiron isometrico en rack (iso-pull)', 'Espalda alta y romboides', 'Isometria de tipo overcoming en patron de traccion. Dorsal a intensidad maxima con fatiga minima.', E'1) Barra fijada en pines a la altura del abdomen, en posicion de remo.\n2) Tirar hacia arriba al maximo 3-5 s. La barra no se mueve.\n3) Soltar progresivamente.\n4) 4-5 repeticiones con 1-2 min entre ellas.'),

-- ---------- ESPALDA BAJA (4) ----------
('Superman', 'Espalda baja', 'Erector espinal para sostener la posicion aero.', E'1) Decubito prono, brazos extendidos al frente.\n2) Elevar simultaneamente brazo y pierna OPUESTOS unos centimetros.\n3) Mantener 2 s sin girar la pelvis ni sacar el cuello.\n4) Bajar y cambiar de lado.\n\n3x10 por lado. La mirada al suelo: no llevar la cabeza atras.'),
('Extension lumbar en banco romano', 'Espalda baja', 'Erector, gluteo e isquios en la posicion del ciclista. La lumbalgia es la queja mas frecuente del ciclista de triatlon.', E'1) Caderas apoyadas en el soporte, pies fijos.\n2) Bajar en bisagra de cadera con la espalda neutra.\n3) Subir extendiendo la cadera hasta la linea del cuerpo. No hiperextender arriba.\n\n3x15 a rango completo.'),
('Hiperextension inversa', 'Espalda baja', 'Erector y gluteo con descarga de la columna. Alternativa cuando la lumbalgia impide cargar de pie.', E'1) Tronco apoyado en el banco, caderas fuera, piernas colgando.\n2) Elevar las piernas hasta la linea del cuerpo contrayendo el gluteo.\n3) Bajar controlado, sin dejar que el peso tire y balancee.\n\nSin impulso: si las piernas van por inercia, el ejercicio no hace nada.'),
('Prone press-up (McKenzie)', 'Espalda baja', 'Es test y ejercicio: si alivia el dolor, apunta a lumbalgia mecanica por flexion prolongada, la tipica del ciclista.', E'1) Decubito prono, manos bajo los hombros.\n2) Extender los codos empujando el tronco hacia arriba.\n3) LA PELVIS NO SE DESPEGA DEL SUELO.\n4) Bajar y repetir 10 veces.\n\nSi ALIVIA o centraliza el dolor hacia la linea media: lumbalgia mecanica, seguir. Si REPRODUCE el dolor o lo irradia a la pierna: posible componente discal, parar y derivar a fisio o medico.'),

-- ---------- HOMBRO Y MANGUITO ROTADOR (14) ----------
('Jalon al pecho', 'Hombro y manguito rotador', 'Progresion de la dominada para quien aun no puede hacerla, con el mismo patron de traccion del crol.', E'1) Sentado, muslos fijos bajo el rodillo, agarre prono ancho.\n2) Tirar de la barra al pecho llevando los codos abajo y atras.\n3) Ligera inclinacion del tronco atras, no mas de 15 grados.\n4) Subir controlado hasta la extension completa.\n\n3x10-12. Nunca por detras de la nuca: es la version que mas hombros de nadador ha creado.'),
('Rotacion externa con banda', 'Hombro y manguito rotador', 'El ejercicio preventivo mas importante del hombro del nadador. Obligatorio para todo triatleta.', E'1) De pie, banda anclada a la altura del codo, en el lado contrario al brazo que trabaja.\n2) Codo pegado al costado y flexionado 90 grados. Se puede sujetar una toalla enrollada en la axila para no despegarlo.\n3) Girar el antebrazo hacia fuera contra la resistencia. El codo NO se mueve del sitio.\n4) Volver controlado.\n\n3x15-20 por brazo. Carga ligera: esto no es un ejercicio de fuerza, es de salud del manguito.'),
('Rotacion interna con banda', 'Hombro y manguito rotador', 'Complemento de la rotacion externa para equilibrar el manguito; el subescapular tambien participa en la traccion.', E'1) Igual que la rotacion externa pero con la banda anclada en el mismo lado del brazo que trabaja.\n2) Codo pegado al costado, flexionado 90 grados.\n3) Girar el antebrazo hacia el abdomen contra la resistencia.\n4) Volver controlado.\n\n3x15.'),
('Rotacion externa en decubito lateral', 'Hombro y manguito rotador', 'Aisla el infraespinoso mejor que la banda de pie.', E'1) Decubito lateral sobre el lado sano, brazo de arriba pegado al costado con el codo a 90 grados.\n2) Mancuerna LIGERA en la mano.\n3) Rotar el antebrazo hacia el techo sin despegar el codo del costado.\n4) Bajar controlado.\n\n3x15. Toalla enrollada bajo la axila para mantener el codo en su sitio.'),
('Face pull', 'Hombro y manguito rotador', 'Deltoides posterior, romboides y rotadores externos.', E'1) Polea o banda a la altura de la cara, agarre de cuerda.\n2) Tirar hacia la cara separando las manos, con los CODOS ALTOS, a la altura de los hombros.\n3) Terminar con las manos a los lados de la cabeza y las escapulas cerradas.\n4) Volver controlado.\n\n3x15. Si los codos caen, se convierte en un remo y pierde el efecto sobre el manguito.'),
('Press de hombro neutro con mancuernas', 'Hombro y manguito rotador', 'Mas seguro que la barra para hombros ya irritados.', E'1) Sentado o de pie, mancuernas a la altura de los hombros, PALMAS ENFRENTADAS.\n2) Empujar hacia arriba sin rotar las palmas.\n3) Bajar controlado hasta la altura de la barbilla.\n\n3x10-12. El agarre neutro reduce el pinzamiento subacromial respecto al agarre pronado.'),
('Press militar con barra', 'Hombro y manguito rotador', 'Empuje vertical: hombro, triceps y pectoral superior, con el core estabilizando de pie.', E'1) De pie, barra a la altura de las clavículas, manos algo mas anchas que los hombros.\n2) Gluteo y abdomen apretados: la lumbar no se arquea.\n3) Empujar arriba metiendo ligeramente la cabeza hacia delante cuando la barra pasa la frente.\n4) Terminar con la barra sobre la vertical del cuerpo.\n\n3x3-6.'),
('Push press', 'Hombro y manguito rotador', 'Version explosiva del press con impulso de piernas. Coordina tren inferior, core y brazos en una sola cadena.', E'1) Posicion de press militar.\n2) Flexion corta y rapida de rodillas, unos 10-15 cm.\n3) Extender las piernas explosivamente y aprovechar el impulso para lanzar la barra arriba.\n4) Terminar el recorrido con los hombros.\n\n3x3-6. El dip es corto y vertical: si el torso se inclina, la barra se va adelante.'),
('Press de hombro con banda', 'Hombro y manguito rotador', 'Empuje vertical con resistencia ascendente, mas amable con el hombro irritado que la mancuerna.', E'1) De pie sobre la banda, extremos en las manos a la altura de los hombros.\n2) Empujar arriba. La banda opone mas resistencia cuanto mas se estira, justo donde el hombro es mas fuerte.\n3) Bajar controlado.'),
('Elevaciones laterales', 'Hombro y manguito rotador', 'Deltoides medio, responsable de sostener el brazo en el recobro del crol.', E'1) De pie, mancuernas ligeras a los lados, codos ligeramente flexionados.\n2) Elevar los brazos por los lados hasta la altura del hombro, no mas.\n3) Bajar controlado en 2-3 s.\n\nSin balanceo del tronco. Si necesitas impulsarte, sobra peso.'),
('Pajaro con mancuernas', 'Hombro y manguito rotador', 'Deltoides posterior, espalda media y manguito: estabilidad y resistencia del hombro en nado de alto volumen.', E'1) Bisagra de cadera hasta casi la horizontal, espalda plana.\n2) Mancuernas colgando, codos ligeramente flexionados.\n3) Elevar los brazos por los lados hasta la altura del hombro.\n4) Controlar la bajada.\n\nSin impulso de piernas ni balanceo del torso.'),
('Wall push-up plus (serrato)', 'Hombro y manguito rotador', 'El serrato anterior estabiliza la escapula durante la traccion; su debilidad es causa de dolor de hombro en nadadores.', E'1) Manos en la pared a la altura de los hombros, cuerpo inclinado en linea recta.\n2) Hacer una flexion contra la pared.\n3) AL FINAL DE CADA REPETICION, empujar un poco mas para protraer activamente la escapula, separandola de la columna.\n4) Volver controlado.\n\n3x15. El "plus" del final es el ejercicio: sin el, es solo una flexion facil.'),
('Wall slide (Y-T-W)', 'Hombro y manguito rotador', 'Activa los estabilizadores escapulares.', E'1) De espaldas a la pared, lumbar, dorsal y cabeza en contacto.\n2) Deslizar los brazos por la pared dibujando una Y, manteniendo el contacto.\n3) Repetir dibujando una T.\n4) Repetir dibujando una W, con los codos bajando hacia los costados.\n\n3x10 por posicion. Si los brazos se despegan de la pared, reducir el rango.'),
('Streamline hold', 'Hombro y manguito rotador', 'Isometria de la posicion hidrodinamica. Trabaja movilidad de hombro y core a la vez.', E'1) De pie contra la pared o tumbado, brazos extendidos sobre la cabeza, manos superpuestas.\n2) Brazos pegados a las orejas, codos rectos.\n3) La lumbar NO se arquea: el abdomen apretado.\n4) Mantener 20-30 s.\n\nSi la lumbar se arquea para llegar, falta movilidad de hombro: trabajarla antes.'),

-- ---------- BICEPS (4) ----------
('Dominada supina (chin-up)', 'Bíceps', 'La opcion mas util del grupo: biceps y dorsal en el mismo patron de traccion del crol.', E'1) Agarre supino (palmas hacia ti) a la anchura de los hombros.\n2) Partir de la extension completa de brazos.\n3) Tirar hasta que la barbilla supere la barra, llevando los codos abajo.\n4) Bajar controlado.\n\nMas facil que la dominada prona: buena progresion hacia ella.'),
('Curl con barra', 'Bíceps', 'Flexion de codo con carga. El biceps participa en la fase de traccion de la brazada.', E'1) De pie, barra con agarre supino a la anchura de los hombros.\n2) Codos pegados al costado y FIJOS: son el eje.\n3) Subir la barra contrayendo el biceps.\n4) Bajar controlado en 2-3 s.\n\nSin balanceo lumbar. Si el tronco se echa atras para subir el peso, sobra carga.'),
('Curl con mancuernas', 'Bíceps', 'Como el curl con barra pero permite supinacion y corrige asimetrias entre brazos.', E'1) De pie, mancuernas a los lados con las palmas hacia dentro.\n2) Subir girando la muneca hasta terminar con la palma hacia arriba.\n3) Bajar controlado deshaciendo el giro.\n\nAlternando brazos o a la vez.'),
('Curl martillo', 'Bíceps', 'Agarre neutro: anade braquial y supinador largo, y carga menos la muneca.', E'1) De pie, mancuernas a los lados con las palmas ENFRENTADAS.\n2) Subir sin girar la muneca, manteniendo el agarre neutro todo el recorrido.\n3) Bajar controlado.'),

-- ---------- TRICEPS (4) ----------
('Extension de triceps en polea alta', 'Tríceps', 'Triceps en la fase de empuje final de la brazada, donde se completa la propulsion.', E'1) De pie frente a la polea alta, agarre de barra o cuerda.\n2) Codos pegados al costado y FIJOS.\n3) Extender los codos hasta abajo del todo.\n4) Volver controlado sin dejar que los codos se abran ni suban.\n\nSolo se mueve el antebrazo.'),
('Extension de triceps sobre la cabeza', 'Tríceps', 'Trabaja la porcion larga del triceps en estiramiento.', E'1) De pie o sentado, mancuerna o banda sujeta con las dos manos por encima de la cabeza.\n2) Bajar por detras de la cabeza flexionando solo los codos.\n3) Codos apuntando al techo y cerca de la cabeza.\n4) Extender arriba.\n\nCore activo para no arquear la lumbar.'),
('Press frances', 'Tríceps', 'Triceps con barra recta o Z tumbado en banco.', E'1) Tumbado, barra sobre el pecho con los brazos extendidos.\n2) Bajar la barra hacia la frente flexionando solo los codos.\n3) Codos apuntando al techo, sin abrirse.\n4) Extender hasta la posicion inicial.\n\nSi los codos se abren, el ejercicio pasa a ser un press y el triceps se libra.'),
('Patada de triceps', 'Tríceps', 'Aislamiento ligero, util como accesorio o en fase de mantenimiento.', E'1) Bisagra de cadera hasta casi la horizontal, o apoyo en banco.\n2) Brazo pegado al cuerpo, codo flexionado 90 grados.\n3) Extender el codo hacia atras hasta la linea del brazo.\n4) Volver controlado.\n\nEl brazo no se mueve: solo el antebrazo. Sin balanceo.'),

-- ---------- CUELLO Y CERVICAL (3) ----------
('Retraccion cervical (doble papada)', 'Cuello y cervical', 'Activa los flexores cervicales profundos. Preventivo de la cervicalgia del ciclista.', E'1) Sentado o de pie, mirada al frente.\n2) Llevar la cabeza hacia atras en horizontal, como haciendo doble papada.\n3) La cabeza NO se inclina ni se agacha: se desplaza hacia atras.\n4) Mantener 3-5 s y soltar.\n\n10-15 repeticiones. Se puede hacer en el coche o en el escritorio.'),
('Isometria cervical multidireccional', 'Cuello y cervical', 'Resistencia de la musculatura cervical sin movimiento articular.', E'1) Mano en la frente: empujar la cabeza contra la mano 10 s sin que se mueva.\n2) Repetir con la mano en la nuca.\n3) Repetir con la mano en cada lateral de la cabeza.\n4) 2-3 vueltas a las cuatro direcciones.\n\nIntensidad moderada, nunca maxima: es musculatura pequena.'),
('Extension cervical en prono', 'Cuello y cervical', 'Entrena los extensores cervicales que la posicion de crono sobrecarga 45-60 grados durante horas.', E'1) Decubito prono en un banco con la cabeza fuera del apoyo, mirando al suelo.\n2) Elevar la cabeza hasta la linea del cuerpo, sin pasarse.\n3) Mantener.\n4) Bajar controlado.\n\nProgresar de 3x10 s a 3x30 s. Empezar sin peso; anadir carga solo cuando 30 s sean comodos.'),

-- ---------- MOVILIDAD Y FLEXIBILIDAD (12) ----------
('Estiramiento de psoas', 'Movilidad y flexibilidad', 'El psoas tenso del ciclista aumenta la lordosis lumbar. Es un desequilibrio clasico del triatleta.', E'1) Zancada larga, rodilla trasera apoyada en el suelo.\n2) METER LA PELVIS EN RETROVERSION: es la clave. Sin esto no se estira el psoas, se arquea la lumbar.\n3) Empujar la cadera adelante manteniendo la pelvis metida.\n4) Mantener 30-60 s por lado.\n\nSi notas el estiramiento en la lumbar y no en la ingle, has perdido la retroversion.'),
('Estiramiento de TFL', 'Movilidad y flexibilidad', 'Parte del tratamiento del sindrome de la cintilla iliotibial.', E'1) De pie, posicion de espadachin lateral: la pierna afectada cruzada por detras de la otra.\n2) Inclinar el tronco hacia el lado CONTRARIO al de la pierna afectada.\n3) Empujar la cadera del lado afectado hacia fuera.\n4) Mantener 30 s por lado.'),
('Estiramiento de isquiotibiales', 'Movilidad y flexibilidad', 'Los isquios cortos impiden mantener la postura en bici sin lumbalgia. Se combina con peso muerto rumano como correctivo.', E'1) De pie o sentado, pierna extendida al frente con el talon apoyado.\n2) Bisagra de cadera hacia delante manteniendo la ESPALDA RECTA.\n3) El estiramiento sale de inclinar la pelvis, no de encorvar la espalda.\n4) Mantener 30 s por lado.'),
('Estiramiento de pantorrilla', 'Movilidad y flexibilidad', 'El acortamiento de pantorrilla del ciclista que luego corre es factor directo de fascitis plantar.', E'1) Manos en la pared, pierna a estirar atrasada, talon en el suelo.\n2) Con la RODILLA EXTENDIDA se estira el gemelo. Mantener 30 s.\n3) Con la RODILLA FLEXIONADA se estira el soleo. Mantener 30 s.\n4) Hacer las dos versiones: trabajan musculos distintos.'),
('Estiramiento de fascia plantar', 'Movilidad y flexibilidad', 'Para la fascitis plantar. El momento de hacerlo importa tanto como el ejercicio.', E'1) Sentado en la cama, cruzar el pie afectado sobre la rodilla contralateral.\n2) Tirar suavemente de los dedos hacia la tibia con la mano.\n3) Mantener 30 s, 3 repeticiones.\n4) REPETIR INMEDIATAMENTE ANTES DE DAR LOS PRIMEROS PASOS DE LA MANANA, que es cuando la fascia esta retraida y duele.'),
('Estiramiento de suboccipitales', 'Movilidad y flexibilidad', 'Para la cervicalgia por respiracion unilateral en natacion.', E'1) Sentado, inclinar la cabeza hacia delante y ligeramente hacia un lado.\n2) Ayudar con la mano sin forzar.\n3) Mantener 30 s por lado.\n\nAcompanar siempre de trabajo de respiracion bilateral: el estiramiento solo trata el sintoma.'),
('Foam roller de TFL y gluteo', 'Movilidad y flexibilidad', 'Liberacion miofascial de TFL y gluteo en el tratamiento de la cintilla iliotibial.', E'1) Rodillo bajo el lateral de la cadera (TFL) apoyando el peso del cuerpo.\n2) Rodar despacio buscando puntos sensibles y parando 20-30 s en ellos.\n3) Pasar al gluteo, sentado sobre el rodillo con el tobillo cruzado sobre la rodilla.\n\nNO PASAR EL RODILLO POR EL EPICONDILO LATERAL DE LA RODILLA: no es efectivo y puede aumentar la inflamacion.'),
('Movilidad de tobillo en pared', 'Movilidad y flexibilidad', 'La falta de dorsiflexion es la causa de que se levanten los talones en la sentadilla. Corregirla antes de cargar.', E'1) De pie frente a la pared, pie a un palmo de ella.\n2) Llevar la rodilla a tocar la pared SIN LEVANTAR EL TALON.\n3) Si llega, alejar el pie un centimetro y repetir. Si no llega, acercarlo.\n4) 10 repeticiones por pierna.\n\nReferencia: unos 10 cm de distancia del pie a la pared. Sirve de test y de ejercicio.'),
('Movilidad toracica en rotacion', 'Movilidad y flexibilidad', 'Una dorsal rigida obliga a la lumbar y al cuello a compensar en posicion aero.', E'1) Decubito lateral, rodillas flexionadas 90 grados y apoyadas en el suelo o en un rulo.\n2) Brazos extendidos al frente, palmas juntas.\n3) Abrir el brazo de arriba en arco hasta el suelo del lado contrario, siguiendolo con la mirada.\n4) LAS RODILLAS NO SE MUEVEN: si se levantan, la rotacion se esta yendo a la lumbar.\n\n10 repeticiones por lado.'),
('Cadera 90/90', 'Movilidad y flexibilidad', 'Recupera el rango de rotacion de cadera que el pedaleo, puramente sagital, nunca entrena.', E'1) Sentado en el suelo, una pierna delante flexionada 90 grados y la otra al lado, tambien a 90.\n2) Espalda recta, tronco erguido.\n3) Rotar las dos piernas al lado contrario sin usar las manos, pasando por el centro.\n4) 10 cambios de lado, pausando 2 s en cada extremo.'),
('Gato-camello', 'Movilidad y flexibilidad', 'Movilizacion suave de la columna. Util como calentamiento o tras sesiones largas de bici.', E'1) Cuadrupedia, manos bajo los hombros y rodillas bajo las caderas.\n2) Redondear la espalda hacia el techo metiendo la pelvis (gato).\n3) Arquearla llevando el pecho al suelo y el coxis al techo (camello).\n4) Alternar despacio, 10-15 ciclos, sin buscar rango maximo.'),
('Movilidad de hombro con palo', 'Movilidad y flexibilidad', 'Rango de hombro para la entrada del crol y la posicion de streamline.', E'1) Palo o banda sujeta por delante con agarre MUY ancho.\n2) Pasarlo por encima de la cabeza hasta atras con los brazos rectos.\n3) Volver por el mismo camino.\n4) 10 repeticiones.\n\nEmpezar con el agarre exageradamente ancho e ir cerrandolo con las semanas. Si hay que doblar los codos, el agarre es demasiado estrecho.'),

-- ---------- CUADRICEPS (13) ----------
('Sentadilla goblet', 'Cuádriceps', 'Puerta de entrada a la sentadilla y opcion tecnica para triatletas con movilidad limitada.', E'1) Mancuerna o kettlebell sujeta al pecho con las dos manos.\n2) Pies a la anchura de los hombros, puntas ligeramente hacia fuera.\n3) Bajar entre las rodillas manteniendo el torso vertical: el contrapeso delante ayuda a no inclinarse.\n4) Subir empujando el suelo.\n\nAdaptacion anatomica: 3x20 al 40% 1RM. Dominar aqui antes de pasar a barra.'),
('Sentadilla trasera con barra', 'Cuádriceps', 'El ejercicio base: cuadriceps, gluteo, isquios y core en un solo movimiento. Transfiere a pedaleo y zancada.', E'1) Pies a la anchura de los hombros, puntas ligeramente hacia fuera (10-15 grados).\n2) Barra sobre los trapecios, NO sobre el cuello.\n3) Descenso: caderas hacia atras y abajo, rodillas en la linea de los pies.\n4) Profundidad minima: muslos paralelos al suelo. Ideal: por debajo del paralelo.\n5) Ascenso: empujar el suelo, torso erguido.\n6) Respiracion: inspirar antes de bajar (Valsalva), expirar al subir.\n\nFuerza maxima: 4x4 al 82-85%.\n\nERRORES: rodillas que colapsan hacia dentro (valgo) = gluteo medio debil, fortalecerlo antes de cargar. Talones que se levantan = falta dorsiflexion de tobillo, trabajar movilidad. Tronco muy inclinado = pasar a frontal o goblet.'),
('Sentadilla frontal', 'Cuádriceps', 'Alternativa para quien se inclina demasiado en la sentadilla trasera por movilidad limitada.', E'1) Barra sobre los deltoides anteriores, no en las manos.\n2) CODOS ALTOS, apuntando al frente: si caen, la barra rueda.\n3) Bajar con el torso vertical, mas que en la trasera.\n4) Subir empujando el suelo.\n\nObliga a un torso mas erguido, por eso perdona menos la falta de movilidad de cadera pero castiga menos la lumbar.'),
('Sentadilla bulgara', 'Cuádriceps', 'El ejercicio numero 1 de ciclismo: el pedaleo es unilateral y cada pierna empuja por separado.', E'1) Pie trasero elevado en un banco, pie delantero adelantado.\n2) Bajar en vertical hasta que la rodilla trasera casi toque el suelo.\n3) El peso en el pie delantero: el trasero solo estabiliza.\n4) Subir empujando con la pierna delantera.\n\n4x8 por pierna con mancuernas o barra. Si la rodilla delantera se va hacia dentro, reducir carga.'),
('Prensa bilateral', 'Cuádriceps', 'Carga las piernas con minima exigencia tecnica y sin cargar la columna. Habitual en adaptacion anatomica.', E'1) Pies a la anchura de los hombros en la plataforma.\n2) Bajar controlado sin que la lumbar se despegue del respaldo.\n3) Empujar sin bloquear las rodillas de golpe arriba.\n\nSi la pelvis bascula abajo, se esta bajando demasiado.'),
('Prensa unilateral', 'Cuádriceps', 'Fuerza de empuje en el rango real del pedaleo.', E'1) Una sola pierna centrada en la plataforma.\n2) Trabajar de 90 a 160 grados de rodilla: ese es el rango del pedaleo.\n3) Empujar sin bloquear.\n\n4x8 por pierna.'),
('Prensa a alta carga y baja repeticion', 'Cuádriceps', 'Fuerza maxima sin exigencia tecnica. Util cuando la sentadilla no es viable por lumbalgia o falta de tecnica.', E'1) Pies a la anchura de los hombros.\n2) Rango algo mas corto que el habitual para permitir mas carga.\n3) 4-5 series de 4-6 repeticiones con 3 min de descanso.\n\nLa lumbar pegada al respaldo en todo momento: es el punto que hace segura esta version.'),
('Zancada caminando', 'Cuádriceps', 'Fuerza unilateral y equilibrio en desplazamiento, patron cercano a la zancada.', E'1) Paso largo al frente, bajando en vertical.\n2) Rodilla delantera DETRAS de la punta del pie.\n3) La rodilla no colapsa hacia dentro.\n4) Empujar con la pierna delantera para pasar al siguiente paso.\n\n3x10-12 pasos por pierna.'),
('Peso muerto con trap bar', 'Cuádriceps', 'Mas cuadriceps y gluteo que el convencional y bastante menos estres lumbar. Buena entrada para quien tiene historial de espalda.', E'1) De pie dentro de la barra hexagonal, agarres a los lados.\n2) Caderas algo mas bajas que en el convencional: se parece mas a una sentadilla.\n3) Empujar el suelo con los pies manteniendo la espalda neutra.\n4) Bajar controlado.\n\n3x3-6. La carga queda en la linea del cuerpo, no por delante: de ahi el menor estres lumbar.'),
('Extension de cuadriceps en maquina', 'Cuádriceps', 'Aislamiento del cuadriceps, util sobre todo en readaptacion tras lesion de rodilla. Poco transferible por si solo.', E'1) Sentado, rodillo sobre el empeine, espalda apoyada.\n2) Extender la rodilla hasta arriba.\n3) Mantener 1 s.\n4) Bajar controlado.\n\nEn readaptacion femoropatelar, evitar los ultimos grados de flexion (mas de 90) porque aumentan la compresion rotuliana.'),
('Jump squat', 'Cuádriceps', 'Convierte la fuerza maxima en potencia de tren inferior.', E'1) Sentadilla hasta media altura, no profunda.\n2) Saltar con la MAXIMA velocidad posible en la fase concentrica.\n3) Caer amortiguando con las rodillas ligeramente flexionadas.\n4) Recolocarse antes de la siguiente.\n\n4x5 al 30-60% 1RM, fase de potencia. La carga es baja porque lo que importa es la velocidad.'),
('Sentadilla con banda en rodillas', 'Cuádriceps', 'La banda obliga a empujar las rodillas hacia fuera: reeduca el valgo bajo carga.', E'1) Banda por encima de las rodillas.\n2) Sentadilla normal, empujando activamente las rodillas CONTRA la banda todo el recorrido.\n3) La banda tira hacia dentro: la tarea es no dejarla ganar.\n\nCarga ligera: es un ejercicio de tecnica, no de fuerza.'),
('Sentadilla isometrica en rack (iso-push)', 'Cuádriceps', 'Isometria de tipo overcoming. Reclutamiento neural sin fatiga excentrica, util cerca de competicion.', E'1) Barra apoyada en pines fijos a la altura de media sentadilla.\n2) Colocarse debajo en posicion de sentadilla y empujar al maximo 3-5 s. La barra no se mueve.\n3) Soltar la tension progresivamente.\n4) 4-5 repeticiones con 2 min entre ellas.\n\nAl no haber fase excentrica, apenas deja fatiga: encaja en semanas con carga alta de resistencia.'),

-- ---------- ISQUIOTIBIALES (9) ----------
('Peso muerto convencional', 'Isquiotibiales', 'Cadena posterior completa: gluteo, isquios, erector y trapecios. Es el motor de la zancada y del pedaleo.', E'1) Barra sobre el dorso del pie, separacion de pies a la anchura de caderas.\n2) Agarre prono (o mixto con cargas altas), manos fuera de las rodillas.\n3) Posicion inicial: caderas altas, espalda recta (ni arqueada ni redondeada), pecho hacia fuera.\n4) Empuje: EMPUJAR EL SUELO CON LOS PIES, no tirar de la barra con la espalda.\n5) Al pasar las rodillas: extender la cadera para erguir el tronco.\n6) Descenso: invertir el movimiento de forma controlada.\n\nFuerza maxima: 4x4 al 82-85%.'),
('Peso muerto rumano bilateral', 'Isquiotibiales', 'Mas util que el convencional para el triatleta: trabaja los isquios en el rango funcional de carrera.', E'1) De pie, barra o mancuernas en las manos.\n2) Bisagra de cadera: empujar las caderas hacia atras manteniendo la espalda neutra.\n3) Bajar hasta sentir el estiramiento de isquiotibiales, NO hasta el suelo.\n4) Volver extendiendo la cadera.\n\nAdaptacion anatomica: 3x15 al 45% 1RM. Las rodillas quedan casi rectas: si se flexionan mucho, se convierte en un peso muerto convencional.'),
('Peso muerto rumano unilateral', 'Isquiotibiales', 'Doble funcion: fuerza de gluteo e isquios en rango de carrera, mas propiocepcion por el equilibrio monopodal. Tambien controla el valgo.', E'1) De pie sobre una pierna, mancuerna en la mano contraria.\n2) Bisagra de cadera sobre esa pierna, bajando la mancuerna hacia el suelo.\n3) La pierna libre se extiende hacia atras como contrapeso, formando una linea con el tronco.\n4) Caderas cuadradas: no dejar que la pelvis rote.\n5) Volver extendiendo la cadera.\n\n3x10 por pierna.'),
('Curl nordico', 'Isquiotibiales', 'De las mayores activaciones de isquiotibial documentadas en EMG.', E'1) De rodillas, un companero sujeta los tobillos (o usar un anclaje).\n2) Dejarse caer hacia delante de forma EXCENTRICA, frenando con los isquiotibiales todo lo posible.\n3) Cuerpo en linea recta de rodillas a cabeza: no romper por la cadera.\n4) Volver a la posicion inicial con ayuda de las manos.\n\n3x5-8 repeticiones excentricas. Si no puedes frenar nada al principio, es normal: frena lo que puedas y amortigua con las manos.'),
('Isometria de isquiotibiales', 'Isquiotibiales', 'Entrada al curl nordico cuando el excentrico completo aun es inasumible.', E'1) Misma posicion que el curl nordico, tobillos sujetos.\n2) Inclinarse hacia delante solo unos grados y MANTENER la posicion.\n3) Aguantar 10-20 s.\n4) Volver con ayuda de las manos.\n\nProgresar aumentando la inclinacion antes de pasar al nordico completo.'),
('Curl femoral en maquina', 'Isquiotibiales', 'Flexion de rodilla aislada, complemento del trabajo de bisagra de cadera. Util para corregir el deficit isquios/cuadriceps del ciclista.', E'1) Tumbado o sentado segun la maquina, rodillo sobre el tendon de Aquiles.\n2) Flexionar la rodilla al maximo.\n3) Bajar controlado en 2-3 s.\n\nLa cadera no se despega del apoyo: si se levanta, sobra peso.'),
('Curl femoral con deslizadores', 'Isquiotibiales', 'Alternativa sin maquina, con componente excentrico y de control lumbopelvico.', E'1) Decubito supino, talones sobre deslizadores o fitball, rodillas flexionadas.\n2) Elevar la cadera hasta la linea del cuerpo.\n3) Extender las piernas deslizando los talones lejos, MANTENIENDO LA CADERA ALTA.\n4) Volver flexionando las rodillas.\n\nSi la cadera cae al extender, reducir el rango.'),
('Good morning', 'Isquiotibiales', 'Bisagra de cadera con barra en la espalda: isquios y erector.', E'1) Barra sobre los trapecios, como en sentadilla.\n2) Bisagra de cadera llevando las caderas atras, rodillas casi rectas.\n3) Bajar hasta que el tronco quede casi horizontal, ESPALDA NEUTRA.\n4) Subir extendiendo la cadera.\n\nCargas moderadas. Tecnica antes que peso: es el ejercicio que menos perdona una espalda redondeada.'),
('Buenos dias con banda', 'Isquiotibiales', 'Bisagra de cadera con resistencia progresiva y carga axial casi nula. Buena opcion en mantenimiento o con historial lumbar.', E'1) De pie sobre la banda, el otro extremo por detras del cuello.\n2) Bisagra de cadera llevando las caderas atras.\n3) Subir extendiendo la cadera contra la banda.\n\nLa banda opone mas cuanto mas arriba, justo donde la cadera es mas fuerte.'),

-- ---------- GLUTEOS (7) ----------
('Hip thrust con barra', 'Glúteos', 'La mayor activacion de gluteo maximo documentada en EMG: mas del 200% del CMV, frente al 87% de la sentadilla.', E'1) Espalda apoyada en un banco por las escapulas, barra sobre las caderas con pad de proteccion.\n2) Pies planos en el suelo, rodillas a 90 grados en la posicion alta.\n3) Elevar la cadera hasta que muslos y torso esten en linea recta.\n4) Contraer el gluteo arriba con 1 s de pausa.\n5) Descenso controlado.\n\nFuerza maxima: 4x5 al 80%. Meter ligeramente la barbilla: la mirada acompana a la cadera, no al techo.'),
('Hip thrust unilateral', 'Glúteos', 'Extension de cadera pierna a pierna, transferible directo al pedaleo y a la zancada. Corrector del gluteo maximo debil.', E'1) Igual que el hip thrust bilateral pero apoyando un solo pie.\n2) La otra pierna flexionada en el aire o extendida.\n3) Subir SIN QUE LA PELVIS ROTE: las dos crestas iliacas a la misma altura.\n4) Pausa arriba y bajada controlada.\n\n3x10 por pierna al 70-75% 1RM.'),
('Puente de gluteo', 'Glúteos', 'Progresion de entrada al hip thrust.', E'1) Decubito supino, rodillas flexionadas, pies planos cerca del gluteo.\n2) Elevar la pelvis hasta la linea de muslos y torso.\n3) Contraer el gluteo arriba.\n4) Bajar controlado sin llegar a apoyar del todo.\n\nPeso corporal, 3x20 en adaptacion anatomica. Si notas los isquios en vez del gluteo, acercar los pies.'),
('Puente de gluteo unilateral', 'Glúteos', 'Test y ejercicio: 30 s sin caida pelvica indica gluteo maximo suficiente. Correctivo de referencia en el protocolo de femoropatelar.', E'1) Decubito supino, un pie apoyado, la otra pierna en el aire.\n2) Elevar la pelvis apoyando en un solo pie.\n3) LA PELVIS NO CAE del lado de la pierna libre: ese es el test.\n4) Mantener o repetir segun el objetivo.\n\n3x15 por lado. Progresar a puente con peso en la semana 3. Como test: aguantar 30 s con la cadera alineada.'),
('Kettlebell swing', 'Glúteos', 'Propulsion explosiva de cadera con core integrado. Transfiere directamente a la fase propulsiva de la zancada.', E'1) Kettlebell en el suelo a un palmo por delante, pies a la anchura de los hombros.\n2) Bisagra de cadera, llevar la pesa entre las piernas hacia atras.\n3) Proyectar la CADERA hacia delante de forma explosiva: la pesa vuela sola, los brazos solo la guian.\n4) Terminar de pie con gluteo y abdomen apretados, pesa a la altura del pecho.\n\n4x10-12 a ritmo explosivo. No es una sentadilla ni una elevacion de brazos: es una bisagra.'),
('Patada de gluteo en polea', 'Glúteos', 'Extension de cadera aislada. Accesorio del hip thrust cuando falta material o hay que reducir carga axial.', E'1) De pie frente a la polea baja, tobillera en un pie.\n2) Llevar la pierna hacia atras extendiendo la cadera.\n3) SIN ARQUEAR LA LUMBAR: el rango sale de la cadera, no de la espalda.\n4) Volver controlado.\n\n3x12-15 por pierna.'),
('Extension de cadera de pie con banda', 'Glúteos', 'Gluteo mayor sin material de gimnasio. Encaja bien en la sesion de mantenimiento de temporada.', E'1) Banda anclada al frente a la altura del tobillo, el otro extremo en un pie.\n2) Sujetarse a algo para no perder el equilibrio.\n3) Llevar la pierna atras contra la banda, sin arquear la lumbar.\n4) Volver controlado.\n\n3x15 por pierna.'),

-- ---------- CADERA Y ADUCTORES (7) ----------
('Clamshell con banda', 'Cadera y aductores', 'Corrector prioritario del gluteo medio debil, el que produce valgo en la sentadilla monopodal.', E'1) Decubito lateral, rodillas flexionadas 45 grados, banda por encima de las rodillas.\n2) Abrir la rodilla superior contra la banda.\n3) LA PELVIS NO RUEDA HACIA ATRAS: si rota, el gluteo medio deja de trabajar. Apoyar la espalda en una pared para notarlo.\n4) Cerrar controlado.\n\nProgresion: semanas 1-2 banda ligera 3x20. Semanas 3-4 banda media 3x15. Semana 5+ banda fuerte con elevacion de cadera simultanea 3x12.'),
('Monster walk', 'Cadera y aductores', 'Gluteo medio y estabilidad lateral del pedaleo.', E'1) Banda elastica en las rodillas o los tobillos.\n2) Posicion de semicuclillas, pecho arriba.\n3) Caminar lateralmente dando pasos amplios, sin juntar los pies del todo.\n4) Mantener la tension de la banda en todo momento.\n\n3x20 pasos por direccion. Las rodillas no colapsan hacia dentro al dar el paso.'),
('Abduccion de cadera en decubito lateral', 'Cadera y aductores', 'Gluteo medio con carga progresiva. Base del protocolo de cintilla iliotibial.', E'1) Decubito lateral, cuerpo alineado, peso en el tobillo de la pierna de arriba.\n2) Elevar la pierna superior sin rotarla: la punta del pie mira al frente, no al techo.\n3) Subir hasta unos 45 grados.\n4) Bajar controlado.\n\n3x15 por lado. Si la punta del pie se gira hacia arriba, el trabajo se va al TFL en vez del gluteo medio.'),
('Abduccion de cadera de pie con banda', 'Cadera y aductores', 'Gluteo medio en cadena cerrada, mas cercano al apoyo de la carrera que el clamshell.', E'1) Banda en los tobillos, de pie, sujeto a un apoyo.\n2) Llevar una pierna al lado contra la banda, tronco erguido.\n3) No inclinar el tronco al lado contrario para ayudarse.\n4) Volver controlado.\n\n3x15 por pierna. Ojo: el gluteo medio que mas trabaja es el de la pierna de APOYO.'),
('Copenhagen plank', 'Cadera y aductores', 'De los mejores ejercicios de aductores, que estabilizan el pedaleo y son foco clasico de lesion por sobreuso.', E'1) Decubito lateral apoyado en el antebrazo, pierna de arriba apoyada en un banco.\n2) Elevar la cadera hasta la linea del cuerpo apretando el aductor de la pierna de arriba.\n3) La pierna de abajo en el aire o apoyada segun el nivel.\n4) Mantener.\n\nPROGRESION: empezar apoyando la RODILLA en el banco (mas facil) antes de pasar al TOBILLO. Empezar con 3x10 s por lado. Es muy exigente: no empezar por la version completa.'),
('Aduccion de cadera en polea', 'Cadera y aductores', 'Aductores con carga progresiva y controlable. Complemento del clamshell, que trabaja el lado opuesto.', E'1) De pie de lado a la polea baja, tobillera en la pierna mas cercana a la maquina.\n2) Llevar esa pierna cruzando por delante de la otra, contra la resistencia.\n3) Volver controlado resistiendo.\n\n3x15 por pierna.'),
('Sentadilla lateral', 'Cadera y aductores', 'Gluteo medio y aductores en el plano frontal. Parte del protocolo de cintilla iliotibial.', E'1) De pie, pies muy separados, puntas al frente.\n2) Desplazar el peso a un lado flexionando esa rodilla mientras la otra pierna queda extendida.\n3) Bajar en bisagra de cadera, pecho arriba.\n4) Volver al centro y cambiar de lado.\n\n3x12 por lado.'),

-- ---------- RODILLA (FORTALECIMIENTO) (7) ----------
('Step-down', 'Rodilla (fortalecimiento)', 'Test y ejercicio a la vez: si aparece valgo, priorizarlo antes de anadir carga.', E'1) De pie sobre un escalon de 20 cm con una pierna.\n2) Bajar la pierna contraria LENTAMENTE controlando el valgo de la rodilla de apoyo.\n3) Rozar el suelo con el talon SIN APOYAR y volver a subir.\n4) La rodilla de apoyo se mantiene alineada con el pie.\n\n3x10 por pierna. Como test: si la rodilla cae hacia dentro, hay que corregir antes de cargar.'),
('Sentadilla monopodal', 'Rodilla (fortalecimiento)', 'Evalua gluteo medio y fuerza unilateral. Es el test funcional clave del sindrome femoropatelar.', E'1) De pie sobre una pierna, brazos al frente para equilibrar.\n2) Bajar flexionando la rodilla todo lo que el control permita.\n3) Observar la rodilla desde el frente, idealmente con video o espejo.\n4) Subir sin apoyar la otra pierna.\n\nREFERENCIAS: 5 repeticiones por pierna sin valgo mayor de 10 grados = correcto. Valgo mayor de 15 grados = sospecha de gluteo medio debil como causa del dolor anterior de rodilla.'),
('Step-up lateral', 'Rodilla (fortalecimiento)', 'Fase de rehabilitacion del sindrome femoropatelar.', E'1) De pie al lado de un escalon.\n2) Subir LATERALMENTE apoyando el pie mas cercano.\n3) Controlar que la rodilla no colapse hacia dentro al subir.\n4) Bajar controlado por el mismo lado.\n\n3x12 por lado. La velocidad de bajada importa mas que la de subida.'),
('Sentadilla con pelota entre rodillas (VMO)', 'Rodilla (fortalecimiento)', 'Enfoca la contraccion del vasto medial, cuya debilidad participa en el mal seguimiento rotuliano.', E'1) De espaldas a la pared, pelota o cojin entre las rodillas.\n2) Bajar en sentadilla apretando la pelota todo el recorrido.\n3) Enfocar la contraccion en la parte interna del cuadriceps, justo encima de la rodilla.\n4) Subir sin dejar de apretar.\n\n3x15.'),
('Extension terminal de rodilla con banda (TKE)', 'Rodilla (fortalecimiento)', 'Vasto medial en los ultimos grados de extension. Habitual en readaptacion de dolor femoropatelar.', E'1) Banda anclada al frente, pasada por detras de la rodilla.\n2) De pie con esa rodilla ligeramente flexionada: la banda tira de ella hacia delante.\n3) Extender la rodilla del todo contra la banda.\n4) Mantener 2 s y volver.\n\n3x15. El rango es corto a proposito: solo los ultimos 30 grados.'),
('Sentadilla isometrica en pared', 'Rodilla (fortalecimiento)', 'La carga isometrica es de las mejor toleradas en tendinopatia rotuliana.', E'1) Espalda contra la pared, pies separados de ella.\n2) Deslizar hasta quedar con las rodillas a 90 grados.\n3) Mantener 30-45 s.\n4) 3-5 repeticiones.\n\nSi 90 grados duelen, subir el angulo hasta encontrar una posicion sin dolor y trabajar ahi.'),
('Spanish squat', 'Rodilla (fortalecimiento)', 'De lo mejor tolerado en tendinopatia rotuliana: permite cargar el tendon con poco dolor.', E'1) Banda gruesa anclada a un poste, pasada por detras de las dos rodillas.\n2) Dejarse caer atras contra la banda: ella sostiene la carga.\n3) Bajar a unos 90 grados de rodilla con el TRONCO VERTICAL.\n4) Mantener 30-45 s.\n\nEl truco es que el torso queda vertical y la tibia tambien: eso concentra la carga en el tendon rotuliano sin cargar la cadera.'),

-- ---------- TOBILLO Y PIE (13) ----------
('Calf raise bilateral', 'Tobillo y pie', 'Fuerza de pantorrilla para la propulsion.', E'1) De pie sobre el borde de un escalon, con el antepie apoyado y los talones en el aire.\n2) Subir de puntillas al maximo.\n3) Bajar hasta notar el estiramiento por debajo del nivel del escalon.\n4) Rango completo, sin rebotes.\n\n3x20 con peso corporal; progresar con chaleco o mancuerna.'),
('Calf raise sentado', 'Tobillo y pie', 'Con la rodilla flexionada el trabajo pasa al soleo, que es el que mas carga soporta al correr y el que el calf raise de pie deja fuera.', E'1) Sentado, peso sobre las rodillas, antepie en un escalon o plataforma.\n2) Subir de puntillas contra el peso.\n3) Bajar controlado hasta el estiramiento.\n\nCon la rodilla flexionada el gemelo queda acortado y no puede trabajar: por eso aisla al soleo.'),
('Calf raise unilateral', 'Tobillo y pie', 'Revela y corrige asimetrias entre piernas.', E'1) De pie sobre un pie en el borde de un escalon, sujeto a un apoyo para el equilibrio.\n2) Subir de puntillas al maximo.\n3) Bajar controlado hasta el estiramiento.\n\nREFERENCIA funcional: 25 repeticiones limpias por pierna. Comparar lados: una diferencia grande explica muchas lesiones unilaterales.'),
('Heel drop excentrico (Alfredson)', 'Tobillo y pie', 'El protocolo con mas respaldo para la tendinopatia del CUERPO del Aquiles (2-6 cm sobre el talon).', E'1) En el borde de un escalon, subir con LAS DOS piernas.\n2) Bajar con UNA SOLA pierna, lentamente (3-4 s).\n3) Volver a subir con las dos: la fase concentrica no cuenta.\n4) 3 series x 15 repeticiones con la rodilla EXTENDIDA.\n5) 3 series x 15 repeticiones con la rodilla FLEXIONADA 30 grados (trabaja el soleo).\n\nFRECUENCIA: 2 veces al dia, 7 dias a la semana, durante 12 semanas. El dolor durante el ejercicio es aceptable hasta 5/10: es la senal de que hay estimulo tendinoso.\n\nNO USAR en tendinopatia INSERCIONAL: ahi el tendon se comprime contra el calcaneo. Usar la isometria en carga.'),
('Plantarflexion excentrica', 'Tobillo y pie', 'Como el heel drop pero enfocado a cargar la fascia plantar.', E'1) En el borde de un escalon, con una toalla enrollada bajo los dedos para mantenerlos en extension.\n2) Subir con las dos piernas.\n3) Bajar lentamente con una, 3-4 s.\n4) La extension de los dedos es lo que pone la fascia en tension.\n\n3x12-15 por pie.'),
('Isometria de triceps sural en carga', 'Tobillo y pie', 'La opcion para la tendinopatia INSERCIONAL, donde el heel drop esta contraindicado. Tambien analgesico en la del cuerpo.', E'1) De pie, sobre una pierna, en SUELO PLANO (no en escalon: el talon no debe caer por debajo).\n2) Subir de puntillas a media altura.\n3) MANTENER la posicion 45 s.\n4) 5 repeticiones con 1-2 min de descanso.\n\nEn tendinopatia insercional, dejar caer el talon comprime el tendon contra el calcaneo y empeora: de ahi el suelo plano. Suele bajar el dolor durante horas tras hacerlo.'),
('Excentrico de tibial posterior', 'Tobillo y pie', 'El tibial posterior es el musculo que tensiona el periostio. Base del tratamiento de la periostitis tibial.', E'1) Sentado, banda anclada al lado externo, rodeando el antepie.\n2) Llevar el pie hacia dentro y arriba (inversion con flexion plantar) contra la banda.\n3) Volver LENTAMENTE, 3-4 s, resistiendo la banda: esa es la fase que cuenta.\n\n3x15 por pie. Junto con la reduccion de carga y la revision de la cadencia (menos de 165 pasos/min aumenta el impacto tibial).'),
('Dorsiflexion de tobillo con banda', 'Tobillo y pie', 'Tibial anterior, antagonista del gemelo, implicado en la absorcion del impacto y en la periostitis tibial.', E'1) Sentado con la pierna extendida, banda anclada al frente y rodeando el antepie.\n2) Llevar la punta del pie hacia la tibia contra la banda.\n3) Volver controlado.\n\n3x15-20 por pie.'),
('Salto de cuerda', 'Tobillo y pie', 'Potencia de pantorrilla y coordinacion neuromuscular del pie.', E'1) Saltos bajos, de 2-3 cm: no hace falta mas.\n2) Contacto con el antepie, talon sin llegar a apoyar.\n3) Rodillas casi rectas: el rebote sale del tobillo, no de la rodilla.\n\n3x1 min continuo o 10x15 s explosivos.'),
('Short foot (pie corto)', 'Tobillo y pie', 'Activa el tibial posterior y los musculos intrinsecos del pie.', E'1) De pie descalzo, peso repartido.\n2) Acortar activamente el pie levantando el arco, acercando la cabeza del primer metatarsiano al talon.\n3) LOS DEDOS NO SE DOBLAN: si se agarran, se esta haciendo trampa.\n4) Mantener 30 s.\n\n3x30 s por pie. Cuesta semanas dominarlo: es puro control motor.'),
('Marble pickup', 'Tobillo y pie', 'Fortalece los intrinsecos del pie.', E'1) Sentado, descalzo, canicas en el suelo.\n2) Recoger una con los dedos del pie y dejarla en un recipiente.\n3) Repetir 20 veces por pie.'),
('Towel curl', 'Tobillo y pie', 'Intrinsecos del pie.', E'1) Sentado, descalzo, con una toalla extendida bajo el pie.\n2) Enrollar la toalla hacia ti solo con los dedos, sin mover el talon.\n3) 3x30 repeticiones.\n\nProgresar poniendo un peso sobre el extremo lejano de la toalla.'),
('Equilibrio unipodal', 'Tobillo y pie', 'Propiocepcion de tobillo, prevencion de esguince y control del valgo.', E'1) De pie sobre una pierna, la otra flexionada sin tocar la de apoyo.\n2) Mantener 30 s vigilando que la rodilla no colapse hacia dentro.\n3) PROGRESION: suelo firme, despues superficie inestable (bosu o cojin), despues ojos cerrados.\n4) Nivel avanzado: lanzarse una pelota mientras se aguanta.\n\n3x30 s por pierna.'),

-- ---------- CORE Y ESTABILIDAD (16) ----------
('Plancha frontal', 'Core y estabilidad', 'Estabilizacion anterior; evita que el tronco oscile en carrera.', E'1) Apoyo en antebrazos y puntas de los pies, codos bajo los hombros.\n2) Cuerpo en linea recta de cabeza a talones.\n3) Gluteo y abdomen apretados, pelvis metida en retroversion.\n4) Respirar con normalidad.\n\n3x30-60 s. REFERENCIA de triatleta: mas de 60 s con forma correcta. Si la cadera se hunde o se levanta, la serie ha terminado aunque queden segundos.'),
('Plancha lateral', 'Core y estabilidad', 'Gluteo medio y oblicuos.', E'1) Decubito lateral, apoyo en el antebrazo con el codo bajo el hombro.\n2) Elevar la cadera hasta que el cuerpo forme una linea recta.\n3) Los hombros y las caderas en el mismo plano: sin rotar el tronco.\n4) Mantener.\n\n3x20-40 s por lado. REFERENCIAS: mas de 40 s = adecuado. Asimetria mayor de 10 s entre lados = desequilibrio lateral, trabajar el lado debil.'),
('Plancha lateral con elevacion de cadera', 'Core y estabilidad', 'Progresion dinamica de la plancha lateral. Parte del protocolo de cintilla iliotibial.', E'1) Partir de la posicion de plancha lateral con la cadera abajo, rozando el suelo.\n2) Elevar la cadera hasta la linea del cuerpo.\n3) Bajar controlado sin apoyar del todo.\n\n3x15 por lado.'),
('Plancha lateral con abduccion', 'Core y estabilidad', 'Gluteo medio bajo carga isometrica de core.', E'1) Posicion de plancha lateral sostenida.\n2) Elevar la pierna superior unos 20 cm, sin rotarla.\n3) Bajar controlado manteniendo la cadera alta todo el rato.\n\n3x10 por lado.'),
('Plancha con elevacion de pierna', 'Core y estabilidad', 'Simula la carga asimetrica del core en el pedaleo.', E'1) Posicion de plancha frontal.\n2) Elevar una pierna 10-15 cm sin que la cadera rote ni se levante.\n3) Mantener 2 s y cambiar.\n\n3x10 por pierna. Lo dificil no es levantar la pierna: es que la pelvis no se mueva.'),
('Dead bug', 'Core y estabilidad', 'Control lumbopelvico en anti-movimiento. Corrector del psoas tenso y del core anterior debil.', E'1) Decubito supino, brazos al techo y caderas y rodillas a 90 grados.\n2) LA LUMBAR PEGADA AL SUELO durante todo el ejercicio: es el objetivo real.\n3) Bajar coordinadamente el brazo y la pierna OPUESTOS hasta rozar el suelo.\n4) Volver y cambiar de lado.\n\n3x10 por lado, lento y controlado. En cuanto la lumbar se despegue, se ha perdido el ejercicio: reducir el rango.'),
('Bird-dog', 'Core y estabilidad', 'Estabilidad rotacional. Fortalece erector y multifido sin carga axial, por eso es base del protocolo de lumbalgia del ciclista.', E'1) Cuadrupedia, manos bajo los hombros y rodillas bajo las caderas.\n2) Extender a la vez el brazo y la pierna OPUESTOS hasta la horizontal.\n3) La pelvis no rota: imaginar un vaso de agua en la lumbar que no se debe derramar.\n4) Volver y cambiar.\n\n3x10 por lado.'),
('Pallof press', 'Core y estabilidad', 'Anti-rotacion pura, el patron que el triatleta necesita. Segun B6-08 es el ejercicio mas especifico para ciclismo.', E'1) Cable o banda a la altura del pecho, de lado, sujeto con las dos manos en el esternon.\n2) Separarse del anclaje hasta tensar.\n3) Empujar el cable hacia delante resistiendo la rotacion del tronco.\n4) Volver al pecho sin dejar que el cable te gire.\n\n3x12 por lado. La resistencia intenta rotarte: la tarea es no dejarla. Para ciclismo, hacerlo desde la posicion inclinada del pedaleo.'),
('Hollow body hold', 'Core y estabilidad', 'Core anterior profundo.', E'1) Decubito supino, brazos extendidos tras la cabeza y piernas rectas.\n2) LUMBAR PEGADA AL SUELO: es el punto de partida innegociable.\n3) Elevar piernas y hombros hasta formar una banana.\n4) Mantener 20-30 s.\n\nSi la lumbar se despega, subir mas las piernas o flexionar las rodillas hasta poder mantenerla pegada.'),
('Ab wheel rollout', 'Core y estabilidad', 'Anti-extension muy exigente, alineado con el principio de anti-movimiento.', E'1) De rodillas, rueda en las manos bajo los hombros.\n2) Pelvis en retroversion y abdomen apretado.\n3) Rodar hacia delante todo lo que se pueda SIN QUE LA LUMBAR SE ARQUEE.\n4) Volver contrayendo el abdomen, no tirando de los brazos.\n\nEl rango lo marca la lumbar, no los brazos. Empezar con recorridos cortos.'),
('Elevacion de rodillas colgado', 'Core y estabilidad', 'Core anterior y resistencia del psoas, con descompresion de la columna por la suspension.', E'1) Colgado de la barra, hombros activos (no colgar muerto).\n2) Elevar las rodillas hacia el pecho metiendo la pelvis al final.\n3) Bajar controlado.\n\n3x12. Sin balanceo: si el cuerpo se columpia, el core no esta trabajando.'),
('Russian twist con balon medicinal', 'Core y estabilidad', 'Rotacion funcional del tronco para el crol. OJO: B3-01 prioriza el anti-movimiento sobre la rotacion dinamica; USA Triathlon lo recomienda. Usar con criterio.', E'1) Sentado en posicion de crunch, tronco inclinado atras, brazos extendidos con el balon.\n2) Rotar el tronco de lado a lado manteniendo LOS BRAZOS RECTOS y el balon a la altura del pecho.\n3) Las caderas permanecen quietas: la rotacion sale del tronco.\n\n3x15 por lado.\n\nCONTEXTO: tus dos fuentes discrepan sobre este ejercicio. B3-01 dice que la columna lumbar es mas estable resistiendo el movimiento que produciendolo. Decidelo por atleta.'),
('Paseo del granjero', 'Core y estabilidad', 'Anti-flexion lateral, agarre y postura bajo carga.', E'1) Una mancuerna o kettlebell pesada en cada mano.\n2) De pie, hombros atras y abajo, pecho arriba.\n3) Caminar con pasos cortos sin inclinarse a ningun lado.\n4) 3-4 recorridos de 20-30 m.\n\nVariante unilateral (una sola mano): mucho mas exigente para el anti-flexion lateral.'),
('Slam de balon medicinal', 'Core y estabilidad', 'Potencia y core en fase de preparacion especifica.', E'1) Balon sobre la cabeza, brazos extendidos, cuerpo estirado.\n2) Lanzarlo contra el suelo con toda la fuerza, acompanando con el tronco.\n3) Recogerlo y repetir sin pausa.\n\n3x8. Usar balon de slam (no rebota): uno normal vuelve a la cara.'),
('Squat thrust con balon medicinal', 'Core y estabilidad', 'Potencia explosiva y estabilidad de core para la rotacion de eje largo del crol.', E'1) Balon sujeto a la altura del hombro.\n2) Sentadilla profunda.\n3) Subir explosivamente extendiendo los brazos sobre la cabeza y soltando el balon.\n4) Recogerlo y repetir.'),
('Zancada caminando con rotacion de balon', 'Core y estabilidad', 'Combina zancada y rotacion de tronco; imita el patron rotacional del crol.', E'1) Balon sujeto con las dos manos al frente.\n2) Zancada adelante bajando en vertical.\n3) Con la pierna adelantada, rotar el tronco HACIA ESE LADO.\n4) Volver al centro y pasar al siguiente paso.\n\nRodilla delantera detras del pie, sin colapso hacia dentro.'),

-- ---------- NATACION — ESPECIFICO (14) ----------
('Cable pull en polea alta', 'Natación — específico', 'La simulacion en seco mas fiel de la traccion del crol.', E'1) De pie frente a la polea alta, un brazo extendido arriba.\n2) Tirar hacia la cadera con el CODO LIGERAMENTE FLEXIONADO, reproduciendo el codo alto del crol.\n3) Ritmo controlado: 2 s por repeticion.\n4) Volver acompanando el cable.\n\n3x15. Lo que se entrena es la trayectoria, no la carga: si hay que dar tirones, sobra peso.'),
('Pallof press horizontal', 'Natación — específico', 'El crol rota el cuerpo 35-45 grados por brazada: el core debe resistir la rotacion excesiva mientras permite la necesaria.', E'1) Cable o banda a la altura del pecho, de lado.\n2) Manos en el esternon, separarse hasta tensar.\n3) Empujar el cable al frente resistiendo la rotacion del tronco.\n4) Volver sin dejar que el cable gire el cuerpo.\n\n3x12 por lado.'),
('Cable woodchop diagonal', 'Natación — específico', 'Simula la rotacion del tronco en la brazada.', E'1) De pie con los pies muy separados, de lado a la polea ALTA.\n2) Agarre con las dos manos, BRAZOS RECTOS como extension del torso.\n3) Tirar en diagonal hacia la cadera contraria, rotando y haciendo sentadilla a la vez.\n4) Volver controlado.\n\n3x12 por lado.'),
('Plancha con rotacion', 'Natación — específico', 'Rotacion controlada del tronco desde una base estable.', E'1) Posicion de plancha frontal.\n2) Abrir un brazo hacia el techo rotando el tronco hasta quedar en plancha lateral.\n3) Seguir la mano con la mirada.\n4) Volver controlado y cambiar de lado.\n\n3x10 por lado.'),
('Remo unilateral de rodillas en polea', 'Natación — específico', 'Fuerza de traccion y estabilidad de hombro con poco estres articular, en una posicion que obliga al core a anti-rotar.', E'1) Arrodillado con una rodilla en el suelo, frente a la polea.\n2) Tirar con el brazo del mismo lado que la rodilla apoyada.\n3) CODO PEGADO AL CUERPO durante todo el tiron.\n4) Volver sin girar el tronco.\n\nLa gracia esta en no rotar: el core trabaja tanto como la espalda.'),
('Gomas de natacion (stretch cords)', 'Natación — específico', 'Simulan la brazada completa en seco. El recurso estandar cuando no hay piscina.', E'1) Gomas ancladas al frente a la altura de la cabeza, un extremo en cada mano.\n2) Inclinar el tronco hacia delante imitando la posicion horizontal.\n3) Traccion completa: entrada, agarre con CODO ALTO, tiron hasta la cadera.\n4) Recobro controlado.\n\nLo importante es reproducir el codo alto: con el codo caido se refuerza el error tecnico.'),
('Dominadas negativas', 'Natación — específico', 'El puente real entre el jalon al pecho y la dominada completa.', E'1) Subir con ayuda (salto o cajon) hasta la posicion alta, barbilla sobre la barra.\n2) BAJAR lo mas lento posible: 5-8 s.\n3) Volver a subir con ayuda: la fase concentrica no cuenta.\n\n3-4 series de 3-5 negativas. La fuerza excentrica llega antes que la concentrica: por eso funciona como progresion.'),
('Sculling', 'Natación — específico', 'El ejercicio del feel for the water: entrena aplicar fuerza hacia atras en vez de hacia fuera, que es lo que separa tener fuerza de saber usarla.', E'1) En el agua, con pullbuoy, brazos al frente y codos algo flexionados.\n2) Movimientos cortos de las manos hacia fuera y hacia dentro, como dibujando ochos.\n3) Buscar la sensacion de PRESION en la palma: eso es agarrar el agua.\n4) Avanzar solo con ese movimiento.\n\n4-6 x 25 m. Variantes: sculling delante, a la altura del pecho y en la cadera.'),
('Batido vertical (vertical kicking)', 'Natación — específico', 'Cuadriceps, core y flexores de cadera. Cuantifica y entrena la potencia del batido.', E'1) En posicion vertical en agua profunda, brazos cruzados sobre el pecho.\n2) Batir de crol para mantenerse a flote con la barbilla fuera.\n3) Batido desde la CADERA, no desde la rodilla; tobillo relajado.\n4) 4-6 x 30 s con descanso.\n\nProgresion: brazos fuera del agua.'),
('Nado con palas', 'Natación — específico', 'Mas superficie de mano, mas resistencia, mas trabajo muscular.', E'1) Palas PEQUENAS O MEDIANAS: las grandes amplifican el torque sobre el hombro y son via directa al hombro del nadador.\n2) Mantener el codo alto: la pala castiga cualquier error tecnico.\n3) Ritmo controlado, no series de maxima intensidad.\n\nMAXIMO 25-30% del volumen de natacion. Eliminarlas por completo ante cualquier molestia de hombro.'),
('Pull set (pullbuoy y palas)', 'Natación — específico', 'Elimina el kick: toda la propulsion viene de los brazos, maximo estimulo de fuerza de traccion.', E'1) Pullbuoy entre los muslos, palas en las manos.\n2) Piernas quietas: no batir.\n3) 4x200 m a ritmo CSS con 30 s de descanso.\n\nOjo si la tecnica es deficiente: el pullbuoy tapa los errores de posicion corporal.'),
('Nado con banda en los tobillos', 'Natación — específico', 'Sin kick posible, obliga a la traccion a sostener la flotacion.', E'1) Banda o goma atando los tobillos, SIN pullbuoy.\n2) Nadar crol sin batir: es imposible.\n3) Toda la flotacion y la propulsion salen de la traccion.\n\nMAXIMO 4x50 m. Alta dificultad tecnica: solo para nadadores con buena traccion. Si se hunden las piernas y se nada en diagonal, aun no toca.'),
('Nado en cuesta con arnes', 'Natación — específico', 'Fuerza de traccion contra resistencia sin salir de la piscina.', E'1) Arnes en la cintura, cuerda elastica atada a la pared.\n2) Nadar alejandose contra la resistencia creciente.\n3) 4-6 x 20-30 s.\n4) Volver suave como recuperacion.'),
('Nado con resistencia de arrastre', 'Natación — específico', 'Anaden arrastre sin alterar el patron de brazada, a diferencia de las palas, que amplifican el torque sobre el hombro.', E'1) Drag socks, paracaidas o camiseta ancha.\n2) Nadar a ritmo controlado: la resistencia ya hace el trabajo.\n3) Series de 50-100 m.\n\nVentaja sobre las palas: la mano trabaja igual, asi que el hombro no recibe torque extra.'),

-- ---------- CICLISMO — ESPECIFICO (7) ----------
('Salidas con resistencia alta en rodillo', 'Ciclismo — específico', 'Fuerza maxima sobre la propia bici.', E'1) En rodillo, aumentar la resistencia al maximo.\n2) Partir desde parado, sentado en el sillin.\n3) Pedalear con todo 8-10 s.\n4) 6-8 repeticiones con 2-3 min de recuperacion.\n\nSentado, no de pie: asi se carga la cadena que interesa. Parar si aparece molestia de rodilla.'),
('Pedaleo unilateral en rodillo', 'Ciclismo — específico', 'Revela y corrige las asimetrias del pedaleo.', E'1) En rodillo, sacar un pie del pedal y apoyarlo en el cuadro o en un cajon.\n2) Pedalear con una sola pierna a 70-80 rpm con resistencia moderada.\n3) Buscar un pedaleo REDONDO: el punto muerto arriba es donde se nota el fallo.\n4) 4x30 s por pierna.\n\nSi el pedaleo se entrecorta arriba, ahi esta la asimetria.'),
('Pedaleo a una pierna con resistencia', 'Ciclismo — específico', 'Aumenta la exigencia sobre la fase de traccion (180-360 grados), que aporta el 20-30% de la potencia.', E'1) Igual que el pedaleo unilateral pero subiendo la resistencia.\n2) Series mas cortas: 20-30 s por pierna.\n3) Enfocar la fase de TIRON, de 180 a 360 grados.\n\nProgresion del pedaleo unilateral una vez este es comodo.'),
('SFR en cuesta (subidas fuerza-resistencia)', 'Ciclismo — específico', 'Fuerza especifica sobre la bici, en la pendiente.', E'1) Pendiente del 5-8%, desarrollo largo.\n2) SENTADO en el sillin, cadencia de 50-60 rpm.\n3) Tronco quieto: si hay que balancearse, el desarrollo es excesivo.\n4) Series de 3-6 min con recuperacion en bajada.\n\nABORTAR si aparece molestia de rodilla: es el ejercicio con mas riesgo del bloque de ciclismo.'),
('Arrancadas en pie', 'Ciclismo — específico', 'Potencia neuromuscular aplicada al pedal.', E'1) Rodando lento con un desarrollo duro.\n2) Levantarse del sillin y esprintar 8-12 s a tope.\n3) Recuperacion completa entre repeticiones: 3-5 min.\n\nEs trabajo neuromuscular: en cuanto la potencia cae, la serie ha terminado.'),
('Sentadilla isometrica en posicion aero', 'Ciclismo — específico', 'Cuadriceps en isometria reproduciendo el angulo de cadera de la posicion de crono.', E'1) Sentadilla a media altura con el TRONCO INCLINADO hacia delante, reproduciendo el angulo de cadera de la posicion aero.\n2) Antebrazos apoyados en un soporte, como en los aerobarres.\n3) Mantener 30-45 s.\n\nEspecifico de crono: replica el angulo de cadera real, no el de la sentadilla de pie.'),
('Isometria en posicion aero', 'Ciclismo — específico', 'B6-08 lo justifica: el ciclismo exige estabilidad en flexion de tronco, no en vertical.', E'1) Plancha con los antebrazos apoyados, reproduciendo la flexion de tronco de 45-55 grados de la posicion aero.\n2) Lumbar neutra: ni arqueada ni redondeada.\n3) Mantener 30-60 s.\n\nEl core generico se entrena en vertical; el del ciclista tiene que aguantar horas en flexion. De ahi que la posicion importe tanto como el ejercicio.'),

-- ---------- CARRERA — ESPECIFICO (12) ----------
('Step-up con mancuernas', 'Carrera — específico', 'Potencia unilateral especifica de la zancada.', E'1) Escalon o cajon de 40-50 cm, mancuernas en las manos.\n2) Apoyar todo el pie en el cajon.\n3) EL PASO HACIA ARRIBA DEBE SER EXPLOSIVO, empujando solo con la pierna de arriba.\n4) Bajar controlado.\n\n4x8 por pierna. No impulsarse con la pierna de abajo: es la trampa habitual.'),
('Step-up explosivo', 'Carrera — específico', 'Version de potencia del step-up, con maxima velocidad y menos carga.', E'1) Cajon mas bajo que en el step-up de fuerza.\n2) Subir a MAXIMA velocidad, llegando a despegar del cajon.\n3) Caer amortiguando y recolocarse.\n\n3x6 por pierna en fase de potencia.'),
('Box jump', 'Carrera — específico', 'Potencia reactiva y vertical.', E'1) De pie frente al cajon, a un paso.\n2) Contramovimiento corto y saltar con los brazos acompanando.\n3) Caer SUAVE sobre el cajon, con las rodillas flexionadas, no aterrizar rigido.\n4) Bajar CAMINANDO, no saltando: la caida desde el cajon es donde se lesiona la gente.\n\n4x5-6. Priorizar velocidad y control sobre altura: no es un concurso de cajon alto.'),
('Depth jump', 'Carrera — específico', 'Ciclo estiramiento-acortamiento. Mejora el stiffness tendinoso y con el la economia de carrera.', E'1) De pie en un cajon de 30-40 cm.\n2) Dejarse caer (no saltar) al suelo.\n3) Al tocar, rebotar hacia arriba con el MINIMO tiempo de contacto posible.\n4) 3x5 con recuperacion completa.\n\nSOLO tras 6-8 semanas de fuerza maxima previa. Superficie blanda las primeras semanas, nunca con fatiga residual, maximo 2 sesiones/semana durante 4-6 semanas.'),
('Single-leg hop horizontal', 'Carrera — específico', 'Potencia unilateral especifica de zancada.', E'1) De pie sobre una pierna.\n2) Saltar hacia delante lo mas lejos posible.\n3) Caer sobre la misma pierna y estabilizar antes del siguiente.\n4) 3x5 por pierna.\n\nSi no puedes estabilizar la caida, aun no toca: trabajar equilibrio unipodal antes.'),
('Bounding', 'Carrera — específico', 'Potencia horizontal y cadencia.', E'1) Zancadas exageradas alternando piernas, buscando maxima distancia por paso.\n2) Rodilla adelantada alta, brazos acompanando amplio.\n3) Fase de vuelo larga: es un salto de pierna a pierna, no una carrera.\n\n3x20 m sobre cesped o superficie blanda.'),
('Ankling', 'Carrera — específico', 'Stiffness de tobillo y cadencia.', E'1) Skipping muy BAJO, con alta frecuencia de contacto.\n2) Contacto solo con el antepie, rodillas casi rectas.\n3) El movimiento sale del tobillo, no de la rodilla ni de la cadera.\n\n4x20 m. Buscar el maximo numero de contactos, no la altura.'),
('Skipping alto (A-skip)', 'Carrera — específico', 'Coordinacion, cadencia y elevacion de rodilla. Tecnica y stiffness a la vez.', E'1) Skipping elevando la rodilla hasta la horizontal.\n2) Tobillo en dorsiflexion, contacto con el antepie bajo el centro de gravedad.\n3) Brazos coordinados en oposicion a las piernas.\n\n4x20 m. Como calentamiento antes de series.'),
('Talones al gluteo', 'Carrera — específico', 'Tecnica de recobro y activacion de isquios. Drill de calentamiento.', E'1) Trote muy corto llevando los talones al gluteo.\n2) El muslo permanece casi vertical: el movimiento es de rodilla, no de cadera.\n3) Alta frecuencia.\n\n3x20 m.'),
('Cuestas cortas (hill sprints)', 'Carrera — específico', 'Fuerza especifica de carrera. Alta transferencia y menos riesgo que el sprint en llano.', E'1) Pendiente del 8-10%.\n2) Esprintar 8-10 s desde parado o casi parado.\n3) Bajar CAMINANDO: recuperacion completa, 2-3 min.\n4) 6-10 repeticiones.\n\nLa cuesta limita la velocidad y por eso protege el isquiotibial: es la forma mas segura de meter potencia de carrera.'),
('Empuje o arrastre de trineo', 'Carrera — específico', 'Extension de cadera contra resistencia horizontal, muy cercana a la fase de propulsion.', E'1) Trineo cargado, arnes o agarre segun la version.\n2) Tronco inclinado hacia delante, pasos potentes y completos.\n3) Buscar la extension completa de cadera en cada paso.\n\n6-8 x 20 m con recuperacion. Carga que permita mantener una mecanica de carrera reconocible: si obliga a caminar, sobra peso.'),
('Strides (zancadas progresivas)', 'Carrera — específico', 'Mecanica y reclutamiento neuromuscular sin la carga de un intervalo.', E'1) Acelerar progresivamente durante 15-20 s hasta un 90-95% del maximo.\n2) Mantener 2-3 s a esa velocidad.\n3) Desacelerar progresivamente.\n4) Recuperacion completa caminando.\n\n6x15 s. Encajan bien al final de un rodaje suave. No son sprints: la progresion es lo importante.')

) as v(nombre, grupo_muscular, descripcion, ejecucion)
where not exists (
  select 1 from ejercicios_biblioteca e where e.nombre = v.nombre
);

-- ============================================================
-- Verificacion (opcional): recuento por grupo tras la carga
-- ============================================================
-- select grupo_muscular, count(*) as ejercicios
-- from ejercicios_biblioteca
-- group by grupo_muscular
-- order by ejercicios desc, grupo_muscular;
