/* ===============================================================
   Cobros: la libreta del entrenador
   =============================================================== */

/* Es un REGISTRO, no una facturacion: no emite facturas, no calcula IVA y no
   cobra. Tres tablas y el saldo es una resta.

   CARGOS Y COBROS, NO UNA CASILLA DE «PAGADO». Esa casilla no aguanta un pago a
   medias, ni un mes con un test ademas de la cuota, ni a quien paga dos meses
   juntos. Con dos listas todo eso sale solo. */

create table if not exists public.tarifa (
  id bigint generated by default as identity primary key,
  id_deportista integer not null references public.deportista(id) on delete cascade,
  /* mensual | sesion | unico */
  tipo text not null,
  importe numeric not null default 0,
  /* Desde cuando se le aplica. Se mira contra el ULTIMO dia del mes, que es
     cuando se cobra: quien empieza el 20 de septiembre paga septiembre. */
  desde date not null,
  hasta date,
  nota text,
  created_at timestamptz not null default now(),
  constraint tarifa_tipo_valido check (tipo in ('mensual', 'sesion', 'unico')),
  constraint tarifa_importe_no_negativo check (importe >= 0)
);

create table if not exists public.cargo (
  id bigint generated by default as identity primary key,
  id_deportista integer not null references public.deportista(id) on delete cascade,
  /* Cuando le corresponde pagarlo. SE COBRA POR VENCIDO: la cuota de septiembre
     lleva fecha del 30 de septiembre, no del 1. De eso depende cuando empieza a
     deber alguien. */
  fecha date not null,
  concepto text not null,
  importe numeric not null,
  /* A que mes pertenece, YYYY-MM. Es lo que agrupa la pantalla. */
  mes text not null,
  tipo text not null,
  created_at timestamptz not null default now(),
  constraint cargo_tipo_valido check (tipo in ('mensual', 'sesion', 'unico')),
  constraint cargo_mes_valido check (mes ~ '^[0-9]{4}-[0-9]{2}$')
);

/* UNA SOLA CUOTA POR PERSONA Y MES. Abrir el mes dos veces no puede cobrar dos
   veces, y eso lo tiene que impedir la base y no el cuidado de quien programa.
   Los cargos sueltos (sesiones, un test) no entran: de esos puede haber varios. */
create unique index if not exists cargo_una_cuota_por_mes
  on public.cargo (id_deportista, mes) where tipo = 'mensual';

create table if not exists public.cobro (
  id bigint generated by default as identity primary key,
  id_deportista integer not null references public.deportista(id) on delete cascade,
  fecha date not null,
  importe numeric not null,
  /* bizum | transferencia | efectivo | otro */
  medio text not null default 'otro',
  nota text,
  created_at timestamptz not null default now(),
  constraint cobro_importe_positivo check (importe > 0)
);

create index if not exists tarifa_id_deportista_idx on public.tarifa (id_deportista);
create index if not exists cargo_id_deportista_idx on public.cargo (id_deportista);
create index if not exists cargo_mes_idx on public.cargo (id_deportista, mes);
create index if not exists cobro_id_deportista_idx on public.cobro (id_deportista);

comment on table public.cargo is
  'Lo que le corresponde pagar a un deportista. Se cobra por vencido: la fecha es el ultimo dia del mes. Ver lib/cobros.ts.';
comment on table public.cobro is 'Lo que ha pagado, con su fecha y su medio.';

/* ===============================================================
   SOLO EL ENTRENADOR. Esto NO lo ve el deportista.
   =============================================================== */

/* OJO, ES DISTINTO DEL RESTO DE LA APLICACION. Sus zonas, su material o sus
   sesiones los ven los dos; el dinero, no. Por eso la politica mira SOLO
   `id_entrenador` y no incluye `id_usuario`: si se copiara la de al lado sin
   pensar, el deportista veria lo que paga y lo que debe. */

alter table public.tarifa enable row level security;
alter table public.cargo enable row level security;
alter table public.cobro enable row level security;

create policy tarifa_solo_su_entrenador on public.tarifa for all
  using (exists (select 1 from public.deportista d
                 where d.id = tarifa.id_deportista and d.id_entrenador = auth.uid()))
  with check (exists (select 1 from public.deportista d
                      where d.id = tarifa.id_deportista and d.id_entrenador = auth.uid()));

create policy cargo_solo_su_entrenador on public.cargo for all
  using (exists (select 1 from public.deportista d
                 where d.id = cargo.id_deportista and d.id_entrenador = auth.uid()))
  with check (exists (select 1 from public.deportista d
                      where d.id = cargo.id_deportista and d.id_entrenador = auth.uid()));

create policy cobro_solo_su_entrenador on public.cobro for all
  using (exists (select 1 from public.deportista d
                 where d.id = cobro.id_deportista and d.id_entrenador = auth.uid()))
  with check (exists (select 1 from public.deportista d
                      where d.id = cobro.id_deportista and d.id_entrenador = auth.uid()));
