/* APLICADA EN PRODUCCION el 2026-09-29. Comprobado: las dos tablas con RLS
   activa y su politica (lectura Y escritura), los dos indices, y el asesor de
   seguridad de Supabase no saca ni un aviso sobre ellas. */

/* ===============================================================
   Material del deportista: zapatillas, bicicletas y sus kilometros
   =============================================================== */

/* El armario de cada deportista. Lo dan de alta los dos: el entrenador desde la
   ficha y el deportista desde su perfil. */

create table if not exists public.material (
  id bigint generated by default as identity primary key,
  id_deportista integer not null references public.deportista(id) on delete cascade,

  /* Solo decide el icono: zapatillas, bicicleta, neopreno, otro. */
  tipo text not null,

  /* ESTO SI DECIDE: es el deporte cuyos kilometros suma. En un brick de 40 km de
     bici y 10 de carrera, la bici suma 40 y las zapatillas 10. */
  disciplina text not null,

  nombre text not null,
  /* «las de placa». Es lo que se lee al elegir en la sesion, porque se reconoce
     antes que «Adizero Adios Pro 3». */
  apodo text,

  /* Los que ya traia encima al darlo de alta. Casi ninguna zapatilla entra en la
     aplicacion a cero, y sin esto el aviso llegaria cientos de kilometros tarde. */
  km_inicial numeric not null default 0,

  /* NULL = sin limite. Lo decide la persona material a material: una zapatilla
     lleva 700, y una bici puede llevar el de su cadena. */
  km_limite numeric,

  /* EL REINICIO ES UNA FECHA, NO UN CERO. Se cambia la cadena: el limite vuelve
     a empezar, pero la bici conserva los kilometros que ha rodado. Por eso se
     guarda CUANDO se reinicio y no se toca el historico. */
  reinicio_fecha date,
  /* El total que llevaba en ese momento. Solo para poder contarlo. */
  reinicio_km numeric,

  /* Jubilado: sigue existiendo con su historia, pero ya no sale a elegir. */
  jubilado boolean not null default false,

  creado_por text,
  created_at timestamptz not null default now()
);

comment on table public.material is
  'Zapatillas, bicicletas y demas de un deportista. Los kilometros NO se guardan aqui: se calculan sumando las sesiones de sesion_material (ver lib/material.ts).';

/* ===============================================================
   Que sesion se hizo con que material
   =============================================================== */

/* UNA SESION PUEDE LLEVAR VARIOS MATERIALES, y por eso esto es una tabla y no
   una columna en `sesion`: un brick se hace con la bici Y con las zapatillas. */

create table if not exists public.sesion_material (
  id_sesion bigint not null references public.sesion(id) on delete cascade,
  id_material bigint not null references public.material(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (id_sesion, id_material)
);

/* La clave primaria ya indexa por sesion; falta la otra direccion, que es la que
   usa la cuenta de kilometros de cada material. */
create index if not exists sesion_material_id_material_idx
  on public.sesion_material (id_material);

create index if not exists material_id_deportista_idx
  on public.material (id_deportista);

/* ===============================================================
   Quien puede ver y tocar esto
   =============================================================== */

/* El propio deportista y su entrenador, igual que el resto de sus datos. */

alter table public.material enable row level security;
alter table public.sesion_material enable row level security;

create policy material_del_deportista_o_su_entrenador
  on public.material for all
  using (exists (
    select 1 from public.deportista d
    where d.id = material.id_deportista
      and (d.id_usuario = auth.uid() or d.id_entrenador = auth.uid())))
  with check (exists (
    select 1 from public.deportista d
    where d.id = material.id_deportista
      and (d.id_usuario = auth.uid() or d.id_entrenador = auth.uid())));

create policy sesion_material_del_deportista_o_su_entrenador
  on public.sesion_material for all
  using (exists (
    select 1 from public.sesion s
    join public.deportista d on d.id = s.id_deportista
    where s.id = sesion_material.id_sesion
      and (d.id_usuario = auth.uid() or d.id_entrenador = auth.uid())))
  with check (exists (
    select 1 from public.sesion s
    join public.deportista d on d.id = s.id_deportista
    where s.id = sesion_material.id_sesion
      and (d.id_usuario = auth.uid() or d.id_entrenador = auth.uid())));
