/* ============================================================
   TRIPULSE - Tests propios del entrenador
   ============================================================

   ADITIVO Y REVERSIBLE. Dos tablas NUEVAS y nada mas: no toca ninguna tabla
   existente, ninguna columna y ninguna politica de las que ya hay. Deshacerlo
   es el bloque del final, y despues de correrlo la base queda exactamente como
   estaba.

   QUE GUARDA CADA UNA

   test_definicion - el test que se crea el entrenador. Sus campos y sus
   resultados van en jsonb y no en tablas aparte: son listas cortas que solo
   lee esta funcionalidad, y una tabla por cada una serian dos joins y dos
   migraciones mas cada vez que un resultado gane un atributo.

     campos:     [{ "clave": "metros", "etiqueta": "Metros en 12 minutos" }]
     resultados: [{ "nombre": "VAM", "unidad": "km/h", "ancla": "vo2max",
                    "formula": [{"t":"var","v":"metros"},
                                {"t":"op","v":"/"},
                                {"t":"num","v":200}],
                    "graf": true }]

   test_medicion - lo que se rellena de un atleta un dia.

     LOS DATOS SON LOS CAMPOS EN BRUTO, NUNCA LOS RESULTADOS. Si manana se
     corrige una formula, el historial entero se corrige solo. Guardando los
     resultados quedarian congelados con la formula vieja, y al mirar la grafica
     no habria forma de saber cual se calculo con cual.

     datos: { "metros": 3200, "pulso_final": 178 }

   POR QUE id_entrenador Y NO id_club
   Hoy los tests son de cada entrenador. Compartirlos dentro de un club se
   hablo y se dejo para mas adelante; cuando llegue, se anade id_club como
   columna opcional y lo que ya haya dentro sigue funcionando. Al reves -
   empezar por el club y luego querer separarlos- si obligaria a migrar.

   RLS
   Cada entrenador ve y toca lo suyo. El atleta NO entra aqui: se acordo que
   los tests propios los rellena solo el entrenador. Cuando eso cambie, se
   anade una politica de lectura mas y ya.
   ============================================================ */

/* === La definicion del test === */

create table if not exists test_definicion (
  id              bigint generated by default as identity primary key,
  /* A perfiles y no a auth.users: es lo que hacen deportista e invitacion, y el
     uuid es el mismo (auth.uid()). Apuntar a auth desde public seria un patron
     nuevo en esta base para no ganar nada. */
  id_entrenador   uuid not null references perfiles(id) on delete cascade,
  nombre          text not null,
  deporte         text not null default 'Carrera',
  campos          jsonb not null default '[]'::jsonb,
  resultados      jsonb not null default '[]'::jsonb,
  archivado       boolean not null default false,
  created_at      timestamptz not null default now()
);

comment on table test_definicion is
  'Tests que se crea el entrenador. campos y resultados en jsonb; ver lib/test-definicion.ts.';
comment on column test_definicion.resultados is
  'Lista de {nombre, unidad, ancla, formula, graf}. El ancla decide si puede gobernar zonas.';

create index if not exists idx_test_definicion_entrenador
  on test_definicion (id_entrenador) where archivado = false;

alter table test_definicion enable row level security;

drop policy if exists test_definicion_suyo on test_definicion;
create policy test_definicion_suyo on test_definicion
  for all using (id_entrenador = auth.uid())
  with check (id_entrenador = auth.uid());

/* === Las mediciones === */

create table if not exists test_medicion (
  id              bigint generated by default as identity primary key,
  id_definicion   bigint not null references test_definicion(id) on delete cascade,
  id_deportista   integer not null references deportista(id) on delete cascade,
  fecha           date not null,
  datos           jsonb not null default '{}'::jsonb,
  created_at      timestamptz not null default now()
);

comment on table test_medicion is
  'Una pasada del test. datos = los CAMPOS en bruto; los resultados se recalculan al leer.';

/* Una medicion por test, atleta y dia: repetir el mismo dia es corregir, no
   apuntar dos veces. Sin esto, el historial y la grafica tendrian dos puntos
   en la misma fecha y ninguno de los dos seria el bueno. */
create unique index if not exists idx_test_medicion_unica
  on test_medicion (id_definicion, id_deportista, fecha);

create index if not exists idx_test_medicion_serie
  on test_medicion (id_definicion, id_deportista, fecha desc);

alter table test_medicion enable row level security;

/* La medicion se ve si se ve su definicion. Asi la regla vive en un sitio: si
   manana se comparten los tests, esto no hay que tocarlo. */
drop policy if exists test_medicion_suyo on test_medicion;
create policy test_medicion_suyo on test_medicion
  for all using (
    exists (select 1 from test_definicion d
            where d.id = test_medicion.id_definicion and d.id_entrenador = auth.uid())
  )
  with check (
    exists (select 1 from test_definicion d
            where d.id = test_medicion.id_definicion and d.id_entrenador = auth.uid())
  );

/* Comprobacion: deben salir las dos tablas con rowsecurity = true */
select tablename, rowsecurity
from pg_tables
where tablename in ('test_definicion', 'test_medicion')
order by tablename;


/* ============================================================
   PARA DESHACERLO
   ============================================================
   Correr esto deja la base exactamente como estaba. Borra los tests propios y
   sus mediciones, y NADA mas: ninguna otra tabla los referencia.

     drop table if exists test_medicion;
     drop table if exists test_definicion;

   ============================================================ */
